# Generated by Django 5.0.8 on 2026-01-07 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_therapistchildassignment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('data', 'Data processing'), ('audio', 'Audio recording'), ('video', 'Video recording'), ('face', 'Face analysis'), ('ai', 'AI-assisted therapy'), ('research', 'Research use')], max_length=20)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents_created', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='patients.guardian')),
            ],
            options={
                'indexes': [models.Index(fields=['child', 'consent_type'], name='compliance__child_i_ba51e6_idx'), models.Index(fields=['guardian'], name='compliance__guardia_fffd90_idx'), models.Index(fields=['granted_at'], name='compliance__granted_652397_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(fields=('child', 'guardian', 'consent_type', 'granted_at'), name='uniq_consent_event'),
        ),
    ]
