# Generated by Django 5.0.8 on 2026-01-07 03:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Undisclosed')], default='undisclosed', max_length=20)),
                ('diagnosis_notes', models.TextField(blank=True, default='')),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('consent_audio', models.BooleanField(default=False)),
                ('consent_video', models.BooleanField(default=False)),
                ('consent_face', models.BooleanField(default=False)),
                ('consent_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(blank=True, default='', max_length=80)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='patients.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TherapistChildAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_therapists', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['created_at'], name='patients_ch_created_a5093e_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['updated_at'], name='patients_ch_updated_19f09b_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['child_profile', 'created_at'], name='patients_gu_child_p_8763c5_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistchildassignment',
            index=models.Index(fields=['therapist'], name='patients_th_therapi_97ebd5_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistchildassignment',
            index=models.Index(fields=['child_user'], name='patients_th_child_u_261177_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='therapistchildassignment',
            unique_together={('therapist', 'child_user')},
        ),
    ]
