# Generated by Django 5.0.8 on 2026-01-07 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='therapistchildassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='primary_language',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='guardian',
            name='is_legal_guardian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistchildassignment',
            name='child_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_therapists', to='patients.childprofile'),
        ),
        migrations.AlterField(
            model_name='therapistchildassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['deleted_at'], name='patients_ch_deleted_0217a2_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['phone'], name='patients_gu_phone_bbc2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistchildassignment',
            index=models.Index(fields=['child_profile'], name='patients_th_child_p_84f601_idx'),
        ),
    ]
