# Generated by Django 5.0.8 on 2026-01-07 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapy_sessions', to='patients.childprofile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapy_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTrial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trial_type', models.CharField(max_length=120)),
                ('prompt', models.TextField(blank=True, default='')),
                ('target_behavior', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='therapy.therapysession')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='therapy.sessiontrial')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='therapy.therapysession')),
            ],
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['child', 'session_date'], name='therapy_the_child_i_68b138_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['therapist', 'session_date'], name='therapy_the_therapi_d5b668_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['status'], name='therapy_the_status_a0aaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['created_at'], name='therapy_the_created_762a56_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontrial',
            index=models.Index(fields=['session', 'created_at'], name='therapy_ses_session_f6c2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontrial',
            index=models.Index(fields=['trial_type'], name='therapy_ses_trial_t_81ec7c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontrial',
            index=models.Index(fields=['status'], name='therapy_ses_status_ea2e00_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['session', 'created_at'], name='therapy_obs_session_feed8e_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['therapist', 'created_at'], name='therapy_obs_therapi_2f5c40_idx'),
        ),
    ]
