# Generated by Django 5.0.8 on 2026-01-07 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_therapy_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='supervision_mode',
            field=models.CharField(choices=[('therapist', 'Therapist'), ('caregiver', 'Caregiver'), ('mixed', 'Mixed')], default='therapist', max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='observation',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
