# Generated by Django 5.0.8 on 2026-01-07 13:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import speech.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASRJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(default='http', max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('result_text', models.TextField(blank=True, default='')),
                ('result_confidence', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asr_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asr_jobs', to='therapy.sessiontrial')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='speech_asrj_status_2bd4a4_idx'), models.Index(fields=['trial', 'created_at'], name='speech_asrj_trial_i_7a7d66_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpeechTrialAudio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=speech.models.speech_audio_upload_path)),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_audio', to='therapy.sessiontrial')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speech_audio_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['uploaded_at'], name='speech_spee_uploade_fd09a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpeechTrialMeta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_text', models.CharField(blank=True, default='', max_length=200)),
                ('target_phoneme', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('therapist_transcript', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_meta', to='therapy.sessiontrial')),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'language'], name='speech_spee_categor_725a45_idx'), models.Index(fields=['difficulty'], name='speech_spee_difficu_36c2e8_idx')],
            },
        ),
    ]
