# Generated by Django 5.0.8 on 2026-01-07 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
        ('therapy', '0002_therapysession_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='speechtrialaudio',
            index=models.Index(fields=['trial'], name='speech_spee_trial_i_24f173_idx'),
        ),
    ]
