# Generated by Django 5.0.8 on 2026-02-08 10:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import speech.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_speechtrialaudio_speech_spee_trial_i_24f173_idx'),
        ('therapy', '0002_therapysession_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('transcript_json', models.JSONField(blank=True, default=dict, help_text='Segments with timestamps')),
                ('vad_json', models.JSONField(blank=True, default=dict, help_text='{"segments": [...], "speech_time_ms": ..., "pause_count": ..., "pause_total_ms": ...}')),
                ('features_json', models.JSONField(blank=True, default=dict, help_text='{"duration_ms": ..., "speech_rate_wpm": ..., "energy_mean": ..., ...}')),
                ('target_score_json', models.JSONField(blank=True, default=dict, help_text='{"keyword_match": 0.8, "text_similarity": 0.7, "missing_keywords": [...]}')),
                ('feedback_json', models.JSONField(blank=True, default=dict, help_text='{"suggestions": [...], "severity": "info"}')),
                ('model_versions', models.JSONField(blank=True, default=dict, help_text='{"asr": "whisper-base", "vad": "silero-v4"}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Speech Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeechRecording',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=speech.models.speech_audio_upload_path)),
                ('consent_snapshot', models.JSONField(blank=True, default=dict, help_text='{"store_audio": false, "retention_days": 0}')),
                ('raw_deleted', models.BooleanField(default=False, help_text='True if raw audio was purged after analysis')),
            ],
        ),
        migrations.RemoveField(
            model_name='speechtrialaudio',
            name='trial',
        ),
        migrations.RemoveField(
            model_name='speechtrialaudio',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='speechtrialmeta',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='speechtrialmeta',
            name='latency_ms',
            field=models.IntegerField(blank=True, help_text='Time from prompt to first speech', null=True),
        ),
        migrations.AddField(
            model_name='speechtrialmeta',
            name='prompt_level',
            field=models.IntegerField(default=0, help_text='0=Full model, 1=Partial, 2=Gesture, 3=Independent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='speechtrialmeta',
            name='therapist_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='speechtrialmeta',
            name='therapist_score',
            field=models.CharField(blank=True, default='', help_text='success/fail/partial', max_length=20),
        ),
        migrations.AlterField(
            model_name='speechtrialmeta',
            name='target_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='SpeechActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('word_repetition', 'Word Repetition'), ('phrase_repetition', 'Phrase Repetition'), ('sentence_repetition', 'Sentence Repetition'), ('picture_naming', 'Picture Naming'), ('yes_no_questions', 'Yes/No Questions'), ('wh_questions', 'WH Questions'), ('minimal_pairs', 'Minimal Pairs'), ('story_retell', 'Story Retell'), ('social_scripts', 'Social Scripts')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('prompt_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('text_image', 'Text + Image')], default='text', max_length=20)),
                ('prompt_payload', models.JSONField(blank=True, default=dict, help_text='{"text": "...", "image_url": "...", "audio_url": "..."}')),
                ('expected_text', models.CharField(blank=True, default='', help_text='Expected response text for scoring', max_length=500)),
                ('language', models.CharField(default='en', max_length=10)),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty_json', models.JSONField(blank=True, default=dict, help_text='Custom difficulty params per level')),
                ('prompt_levels', models.JSONField(blank=True, default=list, help_text='[{"level": 0, "instruction": "Full model"}, {"level": 3, "instruction": "Independent"}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_speech_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Speech Activities',
                'ordering': ['category', 'difficulty_level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='speechtrialmeta',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_metas', to='speech.speechactivity'),
        ),
        migrations.AddIndex(
            model_name='speechtrialmeta',
            index=models.Index(fields=['activity'], name='speech_spee_activit_a3515e_idx'),
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_analyses', to='therapy.sessiontrial'),
        ),
        migrations.AddField(
            model_name='speechrecording',
            name='trial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_recording', to='therapy.sessiontrial'),
        ),
        migrations.AddField(
            model_name='speechrecording',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speech_recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='speech.speechrecording'),
        ),
        migrations.DeleteModel(
            name='SpeechTrialAudio',
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['category'], name='speech_spee_categor_fbbc94_idx'),
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['language'], name='speech_spee_languag_dd1d37_idx'),
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['difficulty_level'], name='speech_spee_difficu_08e98f_idx'),
        ),
        migrations.AddIndex(
            model_name='speechactivity',
            index=models.Index(fields=['is_active'], name='speech_spee_is_acti_7c6c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='speechrecording',
            index=models.Index(fields=['uploaded_at'], name='speech_spee_uploade_bc89f7_idx'),
        ),
        migrations.AddIndex(
            model_name='speechrecording',
            index=models.Index(fields=['trial'], name='speech_spee_trial_i_832786_idx'),
        ),
        migrations.AddIndex(
            model_name='speechanalysis',
            index=models.Index(fields=['trial', 'created_at'], name='speech_spee_trial_i_c218eb_idx'),
        ),
        migrations.AddIndex(
            model_name='speechanalysis',
            index=models.Index(fields=['processing_status'], name='speech_spee_process_3772f4_idx'),
        ),
    ]
