# Generated by Django 5.0.8 on 2026-02-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_speechanalysis_speechrecording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechactivity',
            name='category',
            field=models.CharField(choices=[('word_repetition', 'Word Repetition'), ('phrase_repetition', 'Phrase Repetition'), ('sentence_repetition', 'Sentence Repetition'), ('picture_naming', 'Picture Naming'), ('yes_no_questions', 'Yes/No Questions'), ('wh_questions', 'WH Questions'), ('minimal_pairs', 'Minimal Pairs'), ('story_retell', 'Story Retell'), ('social_scripts', 'Social Scripts'), ('following_directions', 'Following Directions'), ('category_naming', 'Category Naming'), ('verb_usage', 'Verb Usage')], max_length=50),
        ),
    ]
