# Generated by Django 5.0.8 on 2026-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_add_new_activity_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechactivity',
            name='category',
            field=models.CharField(choices=[('repetition', 'Repetition Practice'), ('picture_naming', 'Picture Naming'), ('questions', 'Question & Answer'), ('story_retell', 'Story Retell'), ('category_naming', 'Category Naming')], max_length=50),
        ),
    ]
